# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x08\x65\x63homesh\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"s\n\rLoginResponse\x12)\n\x0bstatus_code\x18\x01 \x01(\x0e\x32\x14.echomesh.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rsession_token\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x03\"S\n\x11RoomActionRequest\x12-\n\x0b\x61\x63tion_type\x18\x02 \x01(\x0e\x32\x18.echomesh.RoomActionType\x12\x0f\n\x07room_id\x18\x03 \x01(\t\"P\n\x12RoomActionResponse\x12)\n\x0bstatus_code\x18\x01 \x01(\x0e\x32\x14.echomesh.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x0bVoicePacket\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x12\n\naudio_data\x18\x02 \x01(\x0c*m\n\nStatusCode\x12\t\n\x05SC_OK\x10\x00\x12\x0c\n\x08SC_ERROR\x10\x01\x12\x16\n\x12SC_UNAUTHENTICATED\x10\x02\x12\x15\n\x11SC_ROOM_NOT_FOUND\x10\x65\x12\x17\n\x13SC_USER_NOT_IN_ROOM\x10\x66*E\n\x0eRoomActionType\x12\x0e\n\nRA_UNKNOWN\x10\x00\x12\x15\n\x11RA_CREATE_OR_JOIN\x10\x01\x12\x0c\n\x08RA_LEAVE\x10\x02\x32\xd5\x01\n\x0f\x45\x63hoMeshService\x12\x38\n\x05Login\x12\x16.echomesh.LoginRequest\x1a\x17.echomesh.LoginResponse\x12G\n\nManageRoom\x12\x1b.echomesh.RoomActionRequest\x1a\x1c.echomesh.RoomActionResponse\x12?\n\x0bStreamAudio\x12\x15.echomesh.VoicePacket\x1a\x15.echomesh.VoicePacket(\x01\x30\x01\x42\x06\x80\x01\x00\x90\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\000\220\001\000'
  _globals['_STATUSCODE']._serialized_start=415
  _globals['_STATUSCODE']._serialized_end=524
  _globals['_ROOMACTIONTYPE']._serialized_start=526
  _globals['_ROOMACTIONTYPE']._serialized_end=595
  _globals['_LOGINREQUEST']._serialized_start=27
  _globals['_LOGINREQUEST']._serialized_end=77
  _globals['_LOGINRESPONSE']._serialized_start=79
  _globals['_LOGINRESPONSE']._serialized_end=194
  _globals['_ROOMACTIONREQUEST']._serialized_start=196
  _globals['_ROOMACTIONREQUEST']._serialized_end=279
  _globals['_ROOMACTIONRESPONSE']._serialized_start=281
  _globals['_ROOMACTIONRESPONSE']._serialized_end=361
  _globals['_VOICEPACKET']._serialized_start=363
  _globals['_VOICEPACKET']._serialized_end=413
  _globals['_ECHOMESHSERVICE']._serialized_start=598
  _globals['_ECHOMESHSERVICE']._serialized_end=811
# @@protoc_insertion_point(module_scope)
