# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import message_pb2 as message__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in message_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EchoMeshServiceStub(object):
    """===================================================================
    1. Service Definition: The core of the gRPC migration
    ===================================================================

    --- Signaling RPCs ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/echomesh.EchoMeshService/Login',
                request_serializer=message__pb2.LoginRequest.SerializeToString,
                response_deserializer=message__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.ManageRoom = channel.unary_unary(
                '/echomesh.EchoMeshService/ManageRoom',
                request_serializer=message__pb2.RoomActionRequest.SerializeToString,
                response_deserializer=message__pb2.RoomActionResponse.FromString,
                _registered_method=True)
        self.StreamAudio = channel.stream_stream(
                '/echomesh.EchoMeshService/StreamAudio',
                request_serializer=message__pb2.VoicePacket.SerializeToString,
                response_deserializer=message__pb2.VoicePacket.FromString,
                _registered_method=True)


class EchoMeshServiceServicer(object):
    """===================================================================
    1. Service Definition: The core of the gRPC migration
    ===================================================================

    --- Signaling RPCs ---
    """

    def Login(self, request, context):
        """Handles user login, returns a session token for subsequent calls.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ManageRoom(self, request, context):
        """Manages room actions like create, join, leave.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAudio(self, request_iterator, context):
        """--- Real-time Audio Streaming RPC ---

        Bidirectional stream for sending and receiving voice data.
        The client continuously sends their audio, and the server continuously
        streams back the audio from other users in the room.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoMeshServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=message__pb2.LoginRequest.FromString,
                    response_serializer=message__pb2.LoginResponse.SerializeToString,
            ),
            'ManageRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.ManageRoom,
                    request_deserializer=message__pb2.RoomActionRequest.FromString,
                    response_serializer=message__pb2.RoomActionResponse.SerializeToString,
            ),
            'StreamAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=message__pb2.VoicePacket.FromString,
                    response_serializer=message__pb2.VoicePacket.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'echomesh.EchoMeshService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('echomesh.EchoMeshService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EchoMeshService(object):
    """===================================================================
    1. Service Definition: The core of the gRPC migration
    ===================================================================

    --- Signaling RPCs ---
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echomesh.EchoMeshService/Login',
            message__pb2.LoginRequest.SerializeToString,
            message__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ManageRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echomesh.EchoMeshService/ManageRoom',
            message__pb2.RoomActionRequest.SerializeToString,
            message__pb2.RoomActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/echomesh.EchoMeshService/StreamAudio',
            message__pb2.VoicePacket.SerializeToString,
            message__pb2.VoicePacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
