#pragma once

#include "message.grpc.pb.h"
#include "UserManager.h"
#include "RoomManager.h"

#include <grpcpp/grpcpp.h>

// This class implements the EchoMeshService gRPC service.
// It inherits from the C++ base class auto-generated by protoc.
class EchoMeshServiceImpl final : public echomesh::EchoMeshService::Service {
public:
    EchoMeshServiceImpl();

    // RPC implementation for user login.
    grpc::Status Login(
        grpc::ServerContext* context, 
        const echomesh::LoginRequest* request, 
        echomesh::LoginResponse* response) override;

    // RPC implementation for room management (join/leave).
    grpc::Status ManageRoom(
        grpc::ServerContext* context, 
        const echomesh::RoomActionRequest* request, 
        echomesh::RoomActionResponse* response) override;

    // RPC implementation for bidirectional audio streaming.
    grpc::Status StreamAudio(
        grpc::ServerContext* context, 
        grpc::ServerReaderWriter<echomesh::VoicePacket, echomesh::VoicePacket>* stream) override;

private:
    // Helper method to get user ID from session token in metadata
    UserId getUserIdFromContext(grpc::ServerContext* context);

    UserManager& m_userManager;
    RoomManager& m_roomManager;
};
